#!/usr/bin/env bash
#Displays the content of the file /etc/passwd, using the while loop + IFS.
i=""
while read -r i
do
	username=$(echo $i | cut -d : -f 1)
  	group_id=$(echo $i | cut -d : -f 4)
  	home_directory=$(echo $i | cut -d : -f 6)
   	command_shell=$(echo $i | cut -d : -f 7)
    	user_id=$(echo $i | cut -d : -f 3)
        password=$(echo $i | cut -d : -f 2)
	user_id_info=$(echo $i | cut -d : -f 5)
	echo "The user $username is part of the $group_id gang, lives in $home_directory and rides $command_shell. $user_id's place is protected by the passcode $password, more info about the user here: $user_id_info"
done < /etc/passwd
