#!/usr/bin/env bash
#Displays Best School 10 times with while.
i=0
while [ $i -le 9 ]; do
	i=$(( i + 1 ))
	if (( i == 4 )); then
		echo "bad luck"
	elif (( i== 8 )); then
		echo "good luck"
	else
		echo "Best School"
	fi
done
