#!/usr/bin/env bash
#Displays To infinity and beyond indefinitely.
trap "rm /var/run/myscript.pid | echo 'I hate the kill command'" 15
trap "rm /var/run/myscript.pid | echo 'Y U no love me?'" 9
trap "rm /var/run/myscript.pid" 3 
while true ; do
	echo "To infinity and beyond"
	sleep 2
done

