#!/usr/bin/env bash
#Manage my process
case $1 in
	start)
		./manage_my_process & echo $! > /var/run/my_process.pid
		echo "manage_my_process started"
		;;
	restart)
	 	kill $(less /var/run/my_process.pid) 
		./manage_my_process & echo $! > /var/run/my_process.pid
		echo "manage_my_process restarted"
		 ;;
	stop)
		kill $(less /var/run/my_process.pid)
		rm /var/run/my_process.pid
		echo "manage_my_process stopped"
		;;
	*)
		echo "Usage: manage_my_process {start|stop|restart}"
		;;
esac
