#!/usr/bin/env bash
#Displays To infinity and beyond indefinitely.
echo $$ > /var/run/myscript.pid
trap "su rm /var/run/myscript.pid | echo 'I hate the kill command'; exit" SIGTERM
trap "echo 'Y U no love me?'" SIGINT
trap "su rm /var/run/myscript.pid; exit" SIGQUIT
while true ; do
	echo "To infinity and beyond"
	sleep 2
done

